# type: ignore[list-item]   # <-- пригодится, если MyPy < 1.10
from typing import List, Optional
from polars import DataFrame 

def scan_excel(path: str) -> List[str]: ...

class PyXlsxEditor:
    def __init__(self, path: str, sheet_name: str) -> None: ...
    def append_row(self, cells: List[str]) -> None: ...
    def append_table_at(self, cells: List[List[str]], start_cell: str) -> None: ...
    def save(self, path: str) -> None: ...
    def last_row_index(self, col_name: str) -> int: ...
    def last_rows_index(self, col_name: str) -> List[int]: ...
    def with_polars(self, df: DataFrame, start_cell: Optional[str]) -> None: ...

class PyXlsxScanner:
    def __init__(self, path: str) -> None: ...
    def get_sheets(self) -> List[str]: ...
    def open_editor(self, sheet_name: str) -> PyXlsxEditor: ...
