# type: ignore[list-item]   # <-- пригодится, если MyPy < 1.10
from typing import List

def scan_excel(path: str) -> List[str]: ...

class PyXlsxEditor:
    def __init__(self, path: str, sheet_name: str) -> None: ...
    def append_row(self, cells: List[str]) -> None: ...
    def append_table_at(self, cells: List[List[str]], start_cell: str) -> None: ...
    def save(self, path: str) -> None: ...
