speed-all:
	cd speed_tests && hyperfine "python excelsior_speed.py" "python openpyxl_speed.py" --export-markdown speed-test.md -M 3
speed-rust:
	cd speed_tests && hyperfine "python excelsior_speed.py" --export-markdown speed-excelsior.md -m 10
